import { JournalEntry, SchoolSettings } from '../types/journal';

export const DEFAULT_SCHOOL_SETTINGS: SchoolSettings = {
  provinceName: 'PEMERINTAH PROVINSI BALI',
  serviceName: 'DINAS PENDIDIKAN KEPEMUDAAN DAN OLAHRAGA',
  schoolName: 'SMA NEGERI 1 TEJAKULA',
  address: 'Jalan Singaraja-Amlapura Desa Tejakula Kecamatan Tejakula Kabupaten Buleleng Provinsi Bali',
  website: 'http://www.smanegerisatutejakula.sch.id',
  email: 'smanegeri1tejakula@gmail.com',
  npsn: '50100282',
  nss: '30.1.22.01.00.037',
  phone: '(0362)3304516',
  postalCode: '81173',
  reportTitle: 'JURNAL KEGIATAN & TARGET KERJA HARIAN',
  reportNote: '*Contoh format jurnal',

  place: 'Tejakula',
  signDate: '1 Oktober 2026',
  signTitle1: 'Ditandatangani secara elektronik oleh:',
  signTitle2: 'Kepala Sekolah',
  principalName: 'Nyoman Sukrada, S.Pd., M.Pd.',
  principalNip: '19680105 199103 1 020',

  teacherName: 'Gede Wijaya, S.Pd.',
  teacherNip: '19860514 201101 1 012',
  teacherRole: 'Guru Mata Pelajaran',
};

export const INITIAL_JOURNAL_ENTRIES: JournalEntry[] = [
  {
    id: 'entry-1',
    date: '2026-10-01',
    dayName: 'Kamis',
    formattedDate: 'Kamis, 1 Okt 2026',
    target: 'Melaksanakan Kegiatan Pembelajaran (KBM) materi Dinamika Rotasi Fisika di kelas XII MIPA 1 jam ke 1-3.',
    status: 'tuntas',
    notes: 'Seluruh peserta didik hadir, evaluasi kuis formatif selesai dilakukan.',
    category: 'Pembelajaran',
    createdAt: '2026-10-01T07:30:00.000Z',
    updatedAt: '2026-10-01T10:15:00.000Z',
  },
  {
    id: 'entry-2',
    date: '2026-10-02',
    dayName: 'Jumat',
    formattedDate: 'Jumat, 2 Okt 2026',
    target: 'Menyusun Modul Ajar dan Lembar Kerja Peserta Didik (LKPD) berbasis Kurikulum Merdeka untuk topik Termodinamika.',
    status: 'tuntas',
    notes: 'Dokumen modul siap diunggah ke portal e-learning sekolah.',
    category: 'Administrasi',
    createdAt: '2026-10-02T08:00:00.000Z',
    updatedAt: '2026-10-02T11:45:00.000Z',
  },
  {
    id: 'entry-3',
    date: '2026-10-03',
    dayName: 'Sabtu',
    formattedDate: 'Sabtu, 3 Okt 2026',
    target: 'Melaksanakan bimbingan remedial dan pengayaan persiapan Asesmen Sumatif Tengah Semester (ASTS) untuk siswa kelas XI.',
    status: 'belum_tuntas',
    notes: 'Perlu dijadwalkan ulang pada hari Senin karena ada kegiatan ekstrakurikuler sekolah.',
    category: 'Bimbingan Siswa',
    createdAt: '2026-10-03T08:30:00.000Z',
    updatedAt: '2026-10-03T12:00:00.000Z',
  },
  {
    id: 'entry-4',
    date: '2026-10-05',
    dayName: 'Senin',
    formattedDate: 'Senin, 5 Okt 2026',
    target: 'Mengikuti rapat koordinasi Dewan Guru SMA Negeri 1 Tejakula terkait evaluasi kedisiplinan dan capaian target kinerja bulanan.',
    status: 'tuntas',
    notes: 'Notulensi rapat telah diserahkan kepada Wakasek Kurikulum.',
    category: 'Tugas Tambahan',
    createdAt: '2026-10-05T07:00:00.000Z',
    updatedAt: '2026-10-05T09:30:00.000Z',
  },
];

export const QUICK_TARGET_SUGGESTIONS = [
  'Melaksanakan kegiatan belajar mengajar (KBM) tatap muka di kelas',
  'Menyusun dan memperbarui Modul Ajar / Rencana Pembelajaran',
  'Melakukan asesmen formatif dan input nilai harian siswa',
  'Memberikan bimbingan remedial & konsultasi tugas siswa',
  'Mengikuti rapat dinas / MGMP internal guru mata pelajaran',
  'Memeriksa kelengkapan administrasi presensi & jurnal kelas',
  'Menyiapkan media pembelajaran digital & presentasi materi',
  'Melaksanakan piket harian dan pengawasan ketertiban lingkungan sekolah',
];
